# UNIQUE TEST NAMES ARE REQUIRED FOR THE UNIVERSES BECAUSE OF THE UniversesIncluded global variable
UNIVERSE = 'Test_Universe'
SUB_UNIVERSE = 'Test_SubUniverse'
NESTED_UNIVERSE = 'Test_NestedUniverse'
PIN = 'Test_PinUniverse'
CELL = 'Test_CellUniverse'
CELL_UNI = 'Test_CellUniverse_Universe'
CELL_MAT = 'Test_CellUniverse_Material'
CELL_OUT = 'Test_CellUniverse_Outside'
LATTICE = 'Test_LatticeUniverse'
LATTICE1 = 'Test_LatticeUniverse1'
LATTICE2 = 'Test_LatticeUniverse2'
FATHER_UNIVERSE = 'Test_FatherUniverse'
DAUGHTER_UNIVERSE = 'Test_DaughterUniverse'

GU3_LIKE = 'T'
GU3_LIKE1 = 'G'
GU3_LIKE2 = 'S'

GEOMETRY_FATHER = 'FATHER'
GEOMETRY_PIN = 'PIN'
GEOMETRY_CELL = 'CELL'
GEOMETRY_LATTICE = 'LATTICE'
